services:
  postgres:
    image: postgres:latest # Specify the PostgreSQL version
    container_name: auth_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # Replace with your desired username
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Replace with your desired password
      POSTGRES_DB: ${POSTGRES_DB} # Replace with your desired database name
    ports:
      - "5432:5432" # Expose PostgreSQL on port 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # Persist data to avoid losing it after restarting the container
    restart: always # Automatically restart the container if it stops

